# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Meredith Smith
tagline:          My Blog
url:             
paginate:         1
baseurl:          /poole
author:
  name:           Meredith Smith
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

